IDIOMS = [
    # ── A1 ──
    ("A1", "a piece of cake", "خیلی راحت، آب خوردن", "something very easy", "The driving test was a piece of cake for her.", "daily"),
    ("A1", "break a leg", "موفق باشی! (قبل از کار مهم)", "used to wish someone good luck", "You have a big show tonight — break a leg!", "luck"),
    ("A1", "under the weather", "سرما خورده، حالش بد", "feeling sick or not well", "I'm a bit under the weather today, so I'll stay home.", "health"),
    ("A1", "hit the road", "راه افتادن، حرکت کردن", "to start a journey or leave", "It's getting late; time to hit the road.", "travel"),
    ("A1", "call it a day", "برای امروز کافیه", "to stop working for the day", "We've done enough — let's call it a day.", "work"),
    ("A1", "rain cats and dogs", "بارون شدید باریدن", "to rain very heavily", "Take an umbrella — it's raining cats and dogs!", "weather"),
    ("A1", "on the house", "مهمان ما، رایگان", "free, paid for by the business", "The waiter said the coffee was on the house.", "money"),
    ("A1", "in a nutshell", "خلاصه و کوتاه بگم", "in a few words, briefly", "In a nutshell, the trip was amazing.", "social"),
    ("A1", "better late than never", "دیر رسیدن بهتر از نرسیدنه", "doing something late is better than not doing it", "He finally called me — better late than never.", "time"),
    ("A1", "time flies", "زمان چه زود می‌گذره", "time passes very quickly", "Time flies when you're having fun.", "time"),
    # ── A2 ──
    ("A2", "cost an arm and a leg", "خیلی گرون بودن", "to be very expensive", "That new phone costs an arm and a leg.", "money"),
    ("A2", "hit the books", "جدی درس خواندن", "to study hard", "Exams start Monday — I have to hit the books.", "study"),
    ("A2", "get cold feet", "دم به تله دادن، ترسیدن در آخرین لحظه", "to suddenly become too nervous to do something", "She got cold feet before the wedding.", "emotions"),
    ("A2", "give someone a hand", "دست کسی رو گرفتن، کمک کردن", "to help someone", "Can you give me a hand with these bags?", "social"),
    ("A2", "hang out", "وقت گذروندن با هم، پر زدن", "to spend time relaxing with friends", "We usually hang out at the café after class.", "social"),
    ("A2", "make up your mind", "تصمیم بگیر دیگه", "to decide", "Make up your mind — tea or coffee?", "daily"),
    ("A2", "once in a blue moon", "هزار سال یه بار", "very rarely", "We eat out once in a blue moon.", "time"),
    ("A2", "on the go", "همیشه سرگرم و در حال حرکت", "very busy and active", "With two kids and a job, she's always on the go.", "daily"),
    ("A2", "save for a rainy day", "برای روز مبادا کنار گذاشتن", "to save money for future problems", "I put a little money aside for a rainy day.", "money"),
    ("A2", "see eye to eye", "هم‌نظر بودن", "to agree with someone", "We don't always see eye to eye on music.", "social"),
    # ── B1 ──
    ("B1", "hit the nail on the head", "درست به هدف زدی، مصداق گفتی", "to describe a situation exactly right", "You hit the nail on the head — that is the real problem.", "social"),
    ("B1", "sit on the fence", "بی‌طرف موندن، تصمیم نگرفتن", "to avoid choosing a side", "Stop sitting on the fence and make a decision!", "emotions"),
    ("B1", "a blessing in disguise", "نعمتی در لباس بلا", "a good thing that seemed bad at first", "Losing that job was a blessing in disguise.", "luck"),
    ("B1", "beat around the bush", "دور و بر دادن، کُنایه رفتن", "to avoid talking about the main point", "Stop beating around the bush and tell me!", "social"),
    ("B1", "let the cat out of the bag", "لو دادن راز", "to reveal a secret by accident", "He let the cat out of the bag about the party.", "social"),
    ("B1", "spill the beans", "فاش کردن راز", "to tell someone a secret", "Come on, spill the beans — what happened?", "social"),
    ("B1", "pull someone's leg", "شوخی ناب کردن با کسی", "to joke with someone", "Relax, I'm just pulling your leg!", "social"),
    ("B1", "the ball is in your court", "توپ توی زمین توئه، نوبت توئه", "it is your turn to take action", "I've made my offer — the ball is in your court now.", "work"),
    ("B1", "burn the midnight oil", "تا دیروقت بیدار موندن برای کار/درس", "to work or study late into the night", "She burned the midnight oil before the exam.", "study"),
    ("B1", "by the book", "دقیقاً طبق قانون", "following the rules exactly", "Our manager does everything by the book.", "work"),
    # ── B2 ──
    ("B2", "cut corners", "از راه نرده رفتن، کم‌کاری کردن", "to do something cheaply or carelessly to save time", "Don't cut corners when safety is involved.", "work"),
    ("B2", "have butterflies in your stomach", "دل‌هراسه، شکمش آب شدن", "to feel very nervous before something", "I had butterflies in my stomach before the speech.", "emotions"),
    ("B2", "jump on the bandwagon", "سوار موج شدن", "to join something because it is popular", "Everyone is jumping on the bandwagon of this new app.", "social"),
    ("B2", "keep your chin up", "ناامید نشو، همتت رو نگه دار", "to stay positive in hard times", "Keep your chin up — things will get better.", "emotions"),
    ("B2", "miss the boat", "فرصت رو از دست دادن", "to miss an opportunity", "Tickets sold out in minutes — we missed the boat.", "luck"),
    ("B2", "no pain, no gain", "بدون زحمت، هیچی نمی‌شه", "you must work hard to get results", "No pain, no gain — keep practicing!", "study"),
    ("B2", "on thin ice", "روی یخ نازک، در موقعیت خطرناک", "in a risky situation", "He's on thin ice with his boss after that mistake.", "work"),
    ("B2", "rock the boat", "به هم ریختن وضعیت آروم", "to cause trouble or upset a stable situation", "Don't rock the boat before the big game.", "work"),
    ("B2", "steal someone's thunder", "دزدیدن توجه و اعتبار دیگری", "to take attention or credit away from someone", "She announced her news at my party and stole my thunder.", "social"),
    ("B2", "the last straw", "قطره‌ای که لیوان رو لبریز کرد", "the final problem that makes a situation unbearable", "His lateness today was the last straw.", "emotions"),
    # ── C1 ──
    ("C1", "bite the bullet", "غصه رو قورت دادن و اقدام کردن", "to do something difficult or unpleasant bravely", "I finally bit the bullet and called the dentist.", "emotions"),
    ("C1", "burn your bridges", "پل‌های پشت سر رو خراب کردن", "to destroy a way back or a relationship", "Don't burn your bridges when you leave a job.", "work"),
    ("C1", "comparing apples to oranges", "مقایسهٔ ناجور", "comparing two things that are too different", "Comparing the two phones is like comparing apples to oranges.", "social"),
    ("C1", "cross that bridge when you come to it", "پل رو موقع رسیدن رد می‌کنیم", "to deal with a problem only when it happens", "Don't worry about it now — we'll cross that bridge when we come to it.", "time"),
    ("C1", "every cloud has a silver lining", "هر بدی یه خوبی توشه", "every bad situation has a good side", "Being fired forced me to study — every cloud has a silver lining.", "luck"),
    ("C1", "hit the sack", "رفتن توی رختخواب", "to go to bed", "I'm exhausted — time to hit the sack.", "daily"),
    ("C1", "method to the madness", "حکمتی پشت رفتار عجیبه", "a logical reason behind strange behaviour", "It looks chaotic, but there's method to the madness.", "work"),
    ("C1", "off the beaten track", "خلوت و دور از مسیر شلوغ", "away from the usual tourist places", "We found a small café off the beaten track.", "travel"),
    ("C1", "put all your eggs in one basket", "همهٔ تخم‌مرغ‌ها توی یه سبد", "to risk everything on one plan", "Don't put all your eggs in one basket — apply to several jobs.", "money"),
    ("C1", "wrap your head around something", "فهمیدن چیز پیچیده", "to understand something complicated", "I can't wrap my head around this math problem.", "study"),
    # ── C2 ──
    ("C2", "a feather in your cap", "افتخاری که به حسابت میاد", "an achievement to be proud of", "Winning the award was a real feather in her cap.", "work"),
    ("C2", "bite off more than you can chew", "از عهده‌ات بزرگ‌تر کار کردن", "to take on more than you can handle", "He bit off more than he could chew with three projects.", "work"),
    ("C2", "flog a dead horse", "تلاش بیهوده رو ادامه دادن", "to waste effort on something that cannot succeed", "Arguing with him is like flogging a dead horse.", "social"),
    ("C2", "throw caution to the wind", "احتیاط رو بذار کنار", "to act without worrying about the risks", "They threw caution to the wind and moved abroad.", "emotions"),
    ("C2", "go down in flames", "با شکست دیدنی تموم شدن", "to fail in a spectacular way", "The startup went down in flames after the scandal.", "work"),
    ("C2", "in the blink of an eye", "در چشم به هم زدنی", "extremely quickly, instantly", "The years passed in the blink of an eye.", "time"),
    ("C2", "kill two birds with one stone", "با یه تیر دو نشون زدن", "to achieve two things with one action", "I killed two birds with one stone by cycling to work — exercise and no traffic.", "daily"),
    ("C2", "speak of the devil", "عجب غیبتی شد!", "said when the person you were talking about appears", "Speak of the devil — here comes Sara!", "social"),
    ("C2", "take it with a grain of salt", "با کمی تردید شنیدن", "to not completely believe something", "Take his stories with a grain of salt.", "social"),
    ("C2", "shoot the breeze", "گپ و قصهٔ بی‌موضوع", "to chat casually about unimportant things", "We sat on the porch and shot the breeze for hours.", "social"),
]
