PLACEMENT_BANK = {
    "A1": [
        {"q": "Choose the correct sentence:", "choices": ["She go to school every day.", "She goes to school every day.", "She going to school every day.", "She gone to school every day."], "answer": 1, "why": "With 'she/he/it' the verb takes -s in present simple: goes."},
        {"q": "I ___ a student.", "choices": ["am", "is", "are", "be"], "answer": 0, "why": "'I' always takes 'am'."},
        {"q": "___ you like coffee?", "choices": ["Does", "Do", "Are", "Is"], "answer": 1, "why": "Questions in present simple with 'you' use 'do'."},
        {"q": "There are ___ apples on the table.", "choices": ["a", "an", "some", "any"], "answer": 2, "why": "'Some' is used in positive sentences with plural nouns."},
        {"q": "What is the opposite of 'hot'?", "choices": ["warm", "cold", "big", "sad"], "answer": 1, "why": "Hot ↔ cold."},
        {"q": "He ___ TV now.", "choices": ["watch", "watches", "is watching", "are watching"], "answer": 2, "why": "'Now' signals present continuous: is + verb-ing."},
        {"q": "This is ___ book. (a/an)", "choices": ["a", "an", "the", "some"], "answer": 0, "why": "'Book' begins with a consonant sound → 'a'."},
        {"q": "We ___ to the park yesterday.", "choices": ["go", "goes", "went", "going"], "answer": 2, "why": "'Yesterday' needs past simple: went."},
    ],
    "A2": [
        {"q": "I have lived here ___ 2019.", "choices": ["for", "since", "from", "at"], "answer": 1, "why": "'Since' is used with a starting point in time; 'for' with a duration."},
        {"q": "She is ___ than her brother.", "choices": ["tall", "taller", "tallest", "more tall"], "answer": 1, "why": "Comparative of short adjectives: +er (taller)."},
        {"q": "They ___ football when it started to rain.", "choices": ["played", "were playing", "are playing", "play"], "answer": 1, "why": "Past continuous (were playing) for an action in progress interrupted by another."},
        {"q": "You ___ smoke in the hospital. It is not allowed.", "choices": ["must", "mustn't", "don't must", "should"], "answer": 1, "why": "'Mustn't' = prohibition."},
        {"q": "I ___ already ___ my homework.", "choices": ["have / finished", "has / finished", "have / finish", "did / finished"], "answer": 0, "why": "Present perfect with 'already': have + past participle."},
        {"q": "If it rains tomorrow, we ___ at home.", "choices": ["will stay", "stay", "stayed", "staying"], "answer": 0, "why": "First conditional: if + present simple, will + verb."},
        {"q": "Which word is a phrasal verb?", "choices": ["beautiful", "give up", "quickly", "happiness"], "answer": 1, "why": "'Give up' = verb + particle."},
        {"q": "There isn't ___ milk in the fridge.", "choices": ["some", "many", "much", "a"], "answer": 2, "why": "'Milk' is uncountable → 'much' in negatives."},
    ],
    "B1": [
        {"q": "I'm not used to ___ up early.", "choices": ["get", "getting", "got", "gets"], "answer": 1, "why": "'Be used to' is followed by a gerund (-ing)."},
        {"q": "The report ___ by the team last week.", "choices": ["wrote", "was writing", "was written", "has written"], "answer": 2, "why": "Passive in past simple: was/were + past participle."},
        {"q": "Unless you hurry, you ___ the bus.", "choices": ["will miss", "miss", "missed", "would miss"], "answer": 0, "why": "'Unless' = if not → first conditional result with will."},
        {"q": "He asked me where ___ the station.", "choices": ["is", "was", "it was", "was it"], "answer": 1, "why": "Reported question: statement order + backshift → where the station was."},
        {"q": "This city is ___ than I expected.", "choices": ["more noisy", "noisier", "noisiest", "most noisy"], "answer": 1, "why": "'Noisy' → noisier (y→ier)."},
        {"q": "Choose the correct idiom: 'The exam was easy — it was a piece of ___.'", "choices": ["bread", "cake", "cheese", "paper"], "answer": 1, "why": "'A piece of cake' = something very easy."},
        {"q": "I wish I ___ more money.", "choices": ["have", "had", "will have", "am having"], "answer": 1, "why": "'I wish' + past simple expresses a present unreal desire."},
        {"q": "You should see a doctor, ___?", "choices": ["should you", "shouldn't you", "do you", "won't you"], "answer": 1, "why": "Question tag mirrors the modal: should → shouldn't."},
    ],
    "B2": [
        {"q": "By the time we arrived, the film ___.", "choices": ["started", "has started", "had started", "was starting"], "answer": 2, "why": "Past perfect for the earlier of two past actions."},
        {"q": "She regrets ___ to the party.", "choices": ["not going", "not go", "to not go", "not to go"], "answer": 0, "why": "'Regret' is followed by a gerund; negative: not + -ing."},
        {"q": "Hardly ___ the door when the phone rang.", "choices": ["I had closed", "had I closed", "I closed", "did I close"], "answer": 1, "why": "Inversion after 'hardly': had + subject + participle."},
        {"q": "The project needs ___ before Friday.", "choices": ["to finish", "finishing", "finished", "being finished"], "answer": 1, "why": "'Need' + gerund = passive meaning (needs to be finished)."},
        {"q": "I'd rather you ___ here alone.", "choices": ["don't stay", "not stay", "didn't stay", "haven't stayed"], "answer": 2, "why": "'I'd rather you' + past simple for present/future preference."},
        {"q": "He denied ___ the money.", "choices": ["to take", "taking", "take", "taken"], "answer": 1, "why": "'Deny' is followed by a gerund."},
        {"q": "Choose the best completion: 'We're planning to ___ the meeting until everyone can attend.'", "choices": ["put off", "put up", "put out", "put down"], "answer": 0, "why": "'Put off' = postpone."},
        {"q": "Not only ___ the competition, but she also broke the record.", "choices": ["she won", "did she win", "won she", "she had won"], "answer": 1, "why": "Inversion after 'not only': did + subject + verb."},
    ],
    "C1": [
        {"q": "___ had he entered the room than everyone fell silent.", "choices": ["Sooner", "No sooner", "Scarcely", "Hardly when"], "answer": 1, "why": "'No sooner... than' with inversion."},
        {"q": "It's high time we ___ something about the traffic.", "choices": ["do", "did", "have done", "will do"], "answer": 1, "why": "'It's high time' + past simple for urgency."},
        {"q": "The new law is expected ___ into effect next year.", "choices": ["to come", "coming", "come", "comes"], "answer": 0, "why": "'Be expected to' + base verb (passive of expect)."},
        {"q": "___ the weather, the match went ahead.", "choices": ["Despite of", "In spite", "In spite of", "Although"], "answer": 2, "why": "'In spite of' + noun phrase; 'despite' takes no 'of'."},
        {"q": "I'd sooner ___ tonight, if it's all the same to you.", "choices": ["stay in", "staying in", "to stay in", "stayed in"], "answer": 0, "why": "'Would sooner' + base verb."},
        {"q": "He spoke ___ he knew the answer, but he was guessing.", "choices": ["as long as", "as though", "even if", "so that"], "answer": 1, "why": "'As though' = as if (unreal comparison)."},
        {"q": "Choose the correct meaning of 'to beat around the bush':", "choices": ["to garden carefully", "to avoid the main topic", "to hurry", "to win easily"], "answer": 1, "why": "It means avoiding the main point."},
        {"q": "Under no circumstances ___ the door unlocked.", "choices": ["you should leave", "should you leave", "you leave", "leave you"], "answer": 1, "why": "Negative adverbials trigger inversion with the modal."},
    ],
    "C2": [
        {"q": "___ John arrived late than the whole schedule fell apart.", "choices": ["Hardly", "Scarcely had", "No sooner had", "Barely"], "answer": 2, "why": "'No sooner had + subject + participle... than' — full inversion."},
        {"q": "The committee's decision was ___; no one could sway it.", "choices": ["waiver", "wavering", "immutable", "imminent"], "answer": 2, "why": "'Immutable' = unchangeable."},
        {"q": "Far from ___ the problem, the update made it worse.", "choices": ["solving", "solve", "to solve", "solved"], "answer": 0, "why": "'Far from' + gerund."},
        {"q": "Were it not for her advice, the deal ___ through.", "choices": ["will fall", "would fall", "would have fallen", "had fallen"], "answer": 2, "why": "'Were it not for' = formal past counterfactual → would have + participle."},
        {"q": "Meaning of 'to bury the hatchet':", "choices": ["to start a conflict", "to end a quarrel and make peace", "to hide evidence", "to dig a garden"], "answer": 1, "why": "It means making peace after a dispute."},
        {"q": "He is said ___ the best pianist of his generation.", "choices": ["being", "to be", "is", "that is"], "answer": 1, "why": "'He is said to be' — passive reporting structure."},
        {"q": "Little ___ that his words would one day be famous.", "choices": ["he knew", "did he know", "knew he", "he did know"], "answer": 1, "why": "'Little' at the start of a sentence triggers inversion in the past: did he know."},
        {"q": "So ___ was the storm that flights were grounded for two days.", "choices": ["furious", "furiousness", "fury", "furiously"], "answer": 0, "why": "'So + adjective + was + noun' — emphatic inversion structure."},
    ],
}
LEVELS_ORDER = ["A1", "A2", "B1", "B2", "C1", "C2"]
