# Generated by Django 5.2.16 on 2026-08-02 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('coins', 'سکه 🪙'), ('gems', 'الماس 💎'), ('xp', 'XP ⚡'), ('points', 'امتیاز 🎯'), ('streak', 'استریک 🔥'), ('item', 'آیتم فروشگاه 🎁'), ('status', 'وضعیت حساب 🚦')], max_length=12, verbose_name='مورد')),
                ('amount', models.IntegerField(default=0, verbose_name='مقدار (+/−)')),
                ('note', models.CharField(blank=True, default='', max_length=220, verbose_name='دلیل')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='جزئیات')),
                ('idempotency_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='کلید یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_actions', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر هدف')),
            ],
            options={
                'verbose_name': 'اقدام پنل',
                'verbose_name_plural': 'اقدامات پنل مدیریت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='pna_user_date_idx'), models.Index(fields=['target', 'created_at'], name='pna_target_date_idx')],
            },
        ),
    ]
