# Generated by Django 5.2.17 on 2026-08-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_alter_usergamestats_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='achievement_type',
            field=models.CharField(choices=[('memory_10', '۱۰ بازی حافظه'), ('puzzle_10', '۱۰ بازی پازل'), ('sudoku_10', '۱۰ بازی سودوکو'), ('iq_10', '۱۰ بازی تست هوش'), ('memory_master', 'استاد حافظه'), ('puzzle_master', 'استاد پازل'), ('sudoku_master', 'استاد سودوکو'), ('iq_master', 'نابغه هوش'), ('language_10', '۱۰ بازی وصل کن'), ('guessing_10', '۱۰ بازی حدس کلمه'), ('scramble_10', '۱۰ بازی جورچین'), ('dictation_10', '۱۰ بازی دیکته صوتی'), ('sprint_10', '۱۰ دوئل کلمات'), ('minesweeper_10', '۱۰ بازی مین\u200cروب'), ('breakout_10', '۱۰ بازی آجرشکن'), ('language_master', 'استاد زبان'), ('word_genius', 'نابغه کلمات')], max_length=30, verbose_name='نوع دستاورد'),
        ),
        migrations.AlterField(
            model_name='usergamestats',
            name='game_name',
            field=models.CharField(choices=[('memory', 'بازی حافظه'), ('puzzle', 'پازل عددی'), ('sudoku', 'سودوکو'), ('iq_test', 'تست هوش'), ('snake', 'بازی مار'), ('2048', 'بازی ۲۰۴۸'), ('reaction', 'تست سرعت واکنش'), ('simon', 'حافظه رنگی سایمون'), ('whack', 'ضربه به موش'), ('tictactoe', 'دوز باهوش'), ('language', 'بازی وصل کن'), ('guessing', 'حدس کلمه'), ('scramble', 'جورچین کلمات'), ('dictation', 'دیکته صوتی'), ('sprint', 'دوئل کلمات'), ('minesweeper', 'مین\u200cروب'), ('breakout', 'آجرشکن')], max_length=20, verbose_name='نام بازی'),
        ),
    ]
