# Generated by Django 5.2.17 on 2026-08-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_userachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True, verbose_name='آخرین روز ثبت\u200cشدهٔ استریک'),
        ),
    ]
