# Generated by Django 5.2.17 on 2026-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_academy', '0006_lesson_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='display_options',
            field=models.JSONField(blank=True, default=dict, verbose_name='تنظیمات نمایش'),
        ),
    ]
