# Generated by Django 5.2.17 on 2026-08-08 11:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_academy', '0007_lessoncontent_display_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('vocab', 'لغت'), ('idiom', 'اصطلاح'), ('mixed', 'ترکیبی')], default='vocab', max_length=10, verbose_name='منبع')),
                ('payload', models.JSONField(default=dict, verbose_name='محتوای چالش')),
                ('answer_index', models.IntegerField(blank=True, null=True, verbose_name='پاسخ کاربر')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='درست بود')),
                ('xp_awarded', models.BooleanField(default=False, verbose_name='پاداش داده شد')),
                ('used_ai', models.BooleanField(default=False, verbose_name='ساخته\u200cشده با AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_challenges', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'چالش هوشمند',
                'verbose_name_plural': 'چالش\u200cهای هوشمند',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(db_index=True, max_length=200, verbose_name='اصطلاح')),
                ('translation_fa', models.CharField(max_length=300, verbose_name='معنی فارسی')),
                ('definition_en', models.CharField(max_length=400, verbose_name='تعریف انگلیسی')),
                ('example_en', models.TextField(verbose_name='مثال انگلیسی')),
                ('example_fa', models.TextField(blank=True, verbose_name='مثال فارسی')),
                ('level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficient')], db_index=True, max_length=2, verbose_name='سطح')),
                ('topic', models.CharField(db_index=True, default='daily', max_length=50, verbose_name='موضوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اصطلاح',
                'verbose_name_plural': 'اصطلاحات',
                'ordering': ['level', 'topic', 'expression'],
                'unique_together': {('expression', 'level')},
            },
        ),
        migrations.CreateModel(
            name='PlacementAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficient')], max_length=2, verbose_name='سطح انتخابی')),
                ('quiz', models.JSONField(default=list, verbose_name='سؤال\u200cها')),
                ('answers', models.JSONField(default=list, verbose_name='پاسخ\u200cها')),
                ('score', models.IntegerField(default=0, verbose_name='نمره')),
                ('verdict', models.CharField(default='pending', max_length=20, verbose_name='نتیجه')),
                ('recommended_level', models.CharField(blank=True, choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficient')], max_length=2, verbose_name='سطح پیشنهادی')),
                ('used_ai', models.BooleanField(default=False, verbose_name='ساخته\u200cشده با AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_attempts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آزمون تعیین سطح',
                'verbose_name_plural': 'آزمون\u200cهای تعیین سطح',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLanguageEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper-Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficient')], default='A1', max_length=2, verbose_name='سطح')),
                ('source', models.CharField(choices=[('self', 'انتخاب کاربر'), ('placement', 'آزمون تعیین سطح')], default='self', max_length=20, verbose_name='منبع')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='language_estimate', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سطح زبانی کاربر',
                'verbose_name_plural': 'سطح\u200cهای زبانی کاربران',
            },
        ),
        migrations.CreateModel(
            name='AIChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'معلم')], max_length=10, verbose_name='نقش')),
                ('content', models.TextField(verbose_name='متن')),
                ('context_type', models.CharField(blank=True, max_length=20, verbose_name='نوع بافت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام معلم هوشمند',
                'verbose_name_plural': 'پیام\u200cهای معلم هوشمند',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='language_ac_user_id_920eb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserIdiomProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='سطح تسلط')),
                ('mastery_score', models.FloatField(default=0, verbose_name='نمره تسلط')),
                ('review_count', models.IntegerField(default=0, verbose_name='تعداد مرور')),
                ('correct_count', models.IntegerField(default=0, verbose_name='تعداد صحیح')),
                ('incorrect_count', models.IntegerField(default=0, verbose_name='تعداد غلط')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='آخرین مرور')),
                ('next_review_date', models.DateTimeField(blank=True, null=True, verbose_name='مرور بعدی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='language_academy.idiom', verbose_name='اصطلاح')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiom_progress', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیشرفت اصطلاح',
                'verbose_name_plural': 'پیشرفت اصطلاحات',
                'indexes': [models.Index(fields=['user', 'next_review_date'], name='language_ac_user_id_977bd6_idx')],
                'unique_together': {('user', 'idiom')},
            },
        ),
    ]
