# Generated by Django 5.2.17 on 2026-08-19 18:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language_academy', '0009_seed_idioms'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گرامر')),
                ('title_fa', models.CharField(blank=True, max_length=200, verbose_name='عنوان فارسی')),
                ('level', models.CharField(choices=[('A1', 'A1 - مبتدی'), ('A2', 'A2 - مقدماتی'), ('B1', 'B1 - متوسط')], default='A1', max_length=2, verbose_name='سطح')),
                ('structure', models.CharField(blank=True, help_text='مثلاً: Subject + am/is/are + ...', max_length=300, verbose_name='فرمول/ساختار')),
                ('explanation', ckeditor.fields.RichTextField(verbose_name='توضیح کامل')),
                ('examples', models.JSONField(default=list, help_text='هر آیتم: {"en": "...", "fa": "..."}', verbose_name='مثال\u200cها')),
                ('common_mistakes', models.TextField(blank=True, verbose_name='اشتباهات رایج')),
                ('usage_tips', models.TextField(blank=True, verbose_name='نکات کاربردی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_points', to='language_academy.lesson', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'نکته گرامری',
                'verbose_name_plural': 'نکات گرامری',
                'ordering': ['lesson__chapter__world__order', 'lesson__chapter__order', 'lesson__order', 'order'],
            },
        ),
    ]
